def handle(e):
    print("Exception raised in " + e)
